language: php

sudo: false

php:
  - 5.6
  - 7
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - composer self-update
  - composer create-project laravel/laravel laravel 5.1
  - cd ./laravel
  - composer require "skimia/assets" dev-master --no-update
  - composer update
  - cd ./vendor/skimia/assets

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi

env:
  global:
    - GIT_NAME: "'Skimia\\Assets'"
    - GIT_EMAIL: kessler.dev@gmail.com
    - GH_REF: github.com/skimia/assets
    - secure: E4UbRsbxVvlgYazU2Um2xpHLydPKkqmXBTeHWiEcD9/uRr/3kWCmb7+9D+UMH1p6nnXcMftzsAg2GOXuJdQaKp6UPo+oBGNQCtnajRQSsh9hZhh3r0UBkLH7NVT7CTjpHSQrG3iZUabH7vuw5dt/zTASynH9JE8r5SL1gA4sXVtBtlF6w8rR6Y76FSrCxYG9XZS/Y5L8VBElCTyooYYPQHv0T1Yvs7HwSK2Zya8WtMwyQE93FikCnaGW/1uB9z+M/533eF0/bHNhZBMRhqMCvECbtsZ29oehzWTiV/1yVwZ8x3/+/pwhjbTHf1gV9GcLFPClCF33KhAf3t3gCwybN+LIvIqiwtS5x3mlGNZDbpyiN/dkNpHz615Br/G8bldO4wujqQyWl0fkBg8vNKD0JG7IT7pXskUkpwQDcxQOvysxO612xw98WCBYE72w1d5guGl+OJByCRTgkX70PM6q+TLrlFzZ2dVLBT7UDn5G+2sae6PzGcoOU8XZeXb3jkBRSc8Xq2gCOo5npWk0GVo45z2uo0lzjDvgMz/TFRouJ33blAsESXhJZTyly4AeVzdJIO2k56EeeBrjxXMQ8RJM3HNhl1ZfN05JJQTmagW2jNja4BzoQ+Ak8X0nHjFyL+uc4MhoJk37ImiJL/gxu1D3c832cVTEUXUNiHVdSmHq8x0=
    - secure: x7855CUZz0S9VoQ1TiDEHC89lCV67BMW1lHXCxKOJTMRXirvNmn0pypFRppo1Qf/cmm2B2ULKCL/gzEAVi559nKNcyOAeEstGnmIjKqZtEUOHFQihZrhk18d74nsY6EA/c8Fm4lmT+yGJAEGWho2cw1XMZY8wZZGsB19hiNChJ1FX1y0aeejC54sOd8K+Pakifjn+22jI2l40vijDMySR56m27jalpR2r0XdImLvIWDQ8teUJymNVpsLZ+RC4OgssYbhtFKiNNb+7Wat59PNw6tOGv2yYfhtX0tnnBx1YcyZ21j+xmJ9DcCksQrPd5UB26fW+HQIvGPmdzb7FOAFR5zqAxjHc+Z42HdHNWYa1UHgW0b4J2k+/paEt8bvcoz2ZP9/9QVpLyc7T/7dmd+ScE8qGspFSzz01hjic0ZxN/O+qpnBRm+0bGf19/c6wJ7tQSYT2XP4wj2FRiB8JWiPLFW6Rp0MopeX56GjXTp3MFD2v7q+Aej2mlCrZ//d2/M6C/46qasipYnByYPpMG3+jjcVmGt28cNAZnhXD9hOb1DsVbVqcolPU7x/0fGf2JRK46Wc536HGUdcZstomRV8YkIqMw/783M0EglY7Yuzekne1t7aHsTLH7lkVEZXJRNP0GzWLeNSG/UTgsZKi+QouMAL21REpryyfxDkkKW5c60=
