language: php
sudo: false
php:
- 5.6
- 7
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_install:
- composer self-update
- composer create-project laravel/laravel laravel 5.1
- cd ./laravel
- composer require "skimia/assets" dev-master --no-update
- composer update
- cd ./vendor/skimia/assets
script:
- phpunit --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
- if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST
  = 'false' ]; then sh generate-api.sh; fi
env:
  global:
  - GIT_NAME: "'Skimia\\Assets'"
  - GIT_EMAIL: kessler.dev@gmail.com
  - GH_REF: github.com/skimia/assets
  - secure: 0WhXejFaYRp1akiT7AbKsJe0XQvCXw9nDg4Qrkoa9mFL7GoaHO+tCOBHGutaJWH9mRV6Vh4bfr00djsc+P1j7iJm9PmfmuSt9xiOYgcbi9TyyLqOkRL9hmkm61l/EoNBiCHXmBDdIFKvyIb3a/H1LOWv4g32Vrn3lQKB/NretSBAOL7gRYomhQtS69+QD6eMwu4YDg7RLwvz8AvPvEU8aVJnCb9pF71o9CSHf5my6mUYUlwWOL4PnZWvqtzJq//ociW4NwV5w7f71qyHm+k8NbkjDJ/s5wMEg3ZRIqux3FZjZ0QNvLjrOYuXTyPB5aWQxAsmQrBcABKeaORK3p5w9eClD76U9mcNUKy498pHHiBbbwvo2qXLFrxgrMLAy/6maTcpWJpQ3b6rUzYXxSe7uKgNjEHkwo2jROPKehIU1BTqqkIwtrdW28NNebNXvNe+pQG3Ui6otRs1epbC9Ldrm7GJKbFDOM/Vj2i1vAe2s/fpxywJ5WxaTn/I0D9SVzNqMRtN44OcCSq5TxdvDXMiiBnJ7d8I9fDn88iaSUQV2sZdgo965r0Jq3W1AFnlM70NazUn6XivFdfCzoY3gDY9yLU0diGYyEgNTy9AYA6lCcLSN1thg+p99K2bl5wqftM5shaxHJsotIR7iL8HqAU6bQ+wOjRgHPyctNehFyZvdzw=
